language: node_js
node_js:
  13

install:
  - npm ci

before_script:
  - psql -c "create database travis_ci_test;" -U postgres
  - bash <(curl -s https://codecov.io/bash)

script:
  - npm run initdb && npm run travistestdb
  - npm run test

services:
  - postgresql